In [1]:
import json
import os
import pandas as pd
import plotly.graph_objects as go

In [2]:
base_path = "eval_results/"
recommenders_path = "overall_metrics_microsoft_recommenders.json"
MF_NMF_path = "overall_metrics_NMF_MF.json"

In [3]:
# Compile data
with open(os.path.join(base_path, recommenders_path), 'r') as file:
    data = json.load(file)

with open(os.path.join(base_path, MF_NMF_path), 'r') as file:
    data["NMF"] = json.load(file)

overall_metrics_df = pd.DataFrame(data)
display(overall_metrics_df)

,ALS,BiVAE,EmbDotBias,NCF,RLRMC,SAR,SASRec,NMF
mean_average_precision,0.009364,0.152553,0.074160,0.030034,0.087530,0.256458,0.027788,0.619222
ndcg_at_k,0.002597,0.021384,0.012292,0.006267,0.014205,0.032611,0.005357,0.743075
precision_at_k,0.035000,0.174947,0.105657,0.064000,0.116935,0.355800,0.040400,0.429400
recall_at_k,0.005957,0.045517,0.023876,0.011861,0.024626,0.070582,0.007844,0.130655
f1_at_k,0.010182,0.072239,0.038950,0.020013,0.040685,0.117797,0.013137,0.173113
hit_rate_at_k,0.272000,0.772824,0.614141,0.330000,0.663306,0.856000,0.168000,0.944000
mean_intra_list_similarity,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.401177
mean_gini_index,0.054441,0.167507,0.024683,0.024932,0.155998,0.156782,0.056959,0.077535
diversity,0.962751,0.624289,0.730087,0.843227,0.690425,0.598259,0.935964,NaN
novelty,15.458591,9.671173,10.162265,11.212175,10.159452,9.621214,13.634492,NaN
distributional_coverage,7.296631,8.238375,7.853805,7.322998,6.920896,7.606307,9.131904,NaN
catalog_coverage,0.124393,0.127901,0.134107,0.108203,0.070426,0.139504,0.302752,0.151646
num_users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.000000
k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000

In [4]:
plotting_df = overall_metrics_df.transpose().reset_index(names="model")
plotting_df

,model,mean_average_precision,ndcg_at_k,precision_at_k,recall_at_k,f1_at_k,hit_rate_at_k,mean_intra_list_similarity,mean_gini_index,diversity,novelty,distributional_coverage,catalog_coverage,num_users,k
0,ALS,0.009364,0.002597,0.035000,0.005957,0.010182,0.272000,0.000000,0.054441,0.962751,15.458591,7.296631,0.124393,NaN,NaN
1,BiVAE,0.152553,0.021384,0.174947,0.045517,0.072239,0.772824,0.000000,0.167507,0.624289,9.671173,8.238375,0.127901,NaN,NaN
2,EmbDotBias,0.074160,0.012292,0.105657,0.023876,0.038950,0.614141,0.000000,0.024683,0.730087,10.162265,7.853805,0.134107,NaN,NaN
3,NCF,0.030034,0.006267,0.064000,0.011861,0.020013,0.330000,0.000000,0.024932,0.843227,11.212175,7.322998,0.108203,NaN,NaN
4,RLRMC,0.087530,0.014205,0.116935,0.024626,0.040685,0.663306,0.000000,0.155998,0.690425,10.159452,6.920896,0.070426,NaN,NaN
5,SAR,0.256458,0.032611,0.355800,0.070582,0.117797,0.856000,0.000000,0.156782,0.598259,9.621214,7.606307,0.139504,NaN,NaN
6,SASRec,0.027788,0.005357,0.040400,0.007844,0.013137,0.168000,0.000000,0.056959,0.935964,13.634492,9.131904,0.302752,NaN,NaN
7,NMF,0.619222,0.743075,0.429400,0.130655,0.173113,0.944000,0.401177,0.077535,NaN,NaN,NaN,0.151646,500.0,10.0

### Precision, recall and F1

In [5]:
import seaborn as sns
import plotly.graph_objects as go

In [12]:

colours = ["#ffb000",  "#dc267f",  "#648fff", "#fe6100", "#785ef0"]  # - IBM colourblind palette


fig = go.Figure(
    data=[
        go.Bar(name='Precision@K', x=plotting_df.model, y=plotting_df.precision_at_k, offsetgroup=1,
               marker_color="#648fff"),
        go.Bar(name='Recall@K', x=plotting_df.model, y=plotting_df.recall_at_k, offsetgroup=2, marker_color= "#dc267f"),
        go.Bar(name='F1@K', x=plotting_df.model, y=plotting_df.f1_at_k, offsetgroup=3, marker_color="#ffb000"),
    ],
    layout={
        #'title': {'text': ''},
        'xaxis': {'title': 'Model'},
        'yaxis': {'title': 'Mean of Precsion/Recall/F1 Score'}
    }
)

# Change the bar mode
fig.update_layout(barmode='group', height=400, width=800)
fig.show()